### ISSUE TITLE
Error install on DietPi

### ISSUE THREAD

**Issue by Djamoussa** [msharov/snownews#73]
Hi.
I'm trying to install snownews from source and i have make error after no warm on configure

`Installing /usr/share/man/man1/snownews.1 ...`
` Installing /usr/share/man/de/man1/snownews.1 ...`
` Installing /usr/share/man/fr/man1/snownews.1 ...`
` Installing /usr/share/man/it/man1/snownews.1 ...`
` Installing /usr/share/man/nl/man1/snownews.1 ...`
` Installing /usr/share/man/ru/man1/snownews.1 ...`
`    compiling po/be@latin.po ...`
`make: msgfmt: Aucun fichier ou dossier de ce type`
`make: *** [po/Module.mk:42 : .o/po/be@latin.mo] Erreur 127`

Thx

**Comment by msharov** [comment]
Should be fixed by commit a534490236a0a6958d01dd1202d0303a6ad8e301

**Comment by Djamoussa** [comment]
Still the same on my side 

`Installing /usr/share/man/man1/snownews.1 ...`
` Installing /usr/share/man/de/man1/snownews.1 ...`
` Installing /usr/share/man/fr/man1/snownews.1 ...`
` Installing /usr/share/man/it/man1/snownews.1 ...`
` Installing /usr/share/man/nl/man1/snownews.1 ...`
` Installing /usr/share/man/ru/man1/snownews.1 ...`
`    compiling po/be.po ...`
`make: msgfmt: Aucun fichier ou dossier de ce type`
`make: *** [po/Module.mk:42 : .o/po/be.mo] Erreur 127`

**Comment by msharov** [comment]
If it isn't the .po file, it must be msgfmt. Make sure you have /usr/bin/msgfmt installed. It is part of the gettext package. Or run `./configure --without-nls` to disable localization.
